# apiVersion: v1
# kind: Namespace
# metadata:
#   name: wordpress

# ---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-db
    tier: backend
    env: prod
    customer: tuke
  name: wp-db
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
        customer: tuke
    spec:
      containers:
      - image: mariadb
        name: mariadb
        envFrom:
        - configMapRef:
            name: wordpress
        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc      

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-db
  name: wp-db
  namespace: wordpress
spec:
  ports:
  - name: mariadb
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: db
  type: ClusterIP

---

apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: wordpress
data:
  WORDPRESS_DB_HOST: d3AtZGI=
  WORDPRESS_DB_NAME: d29yZHByZXNz
  WORDPRESS_DB_PASSWORD: ZW5kMzIx
  WORDPRESS_DB_USER: d3B1c2Vy

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-app
    tier: frontend
    env: prod
    customer: tuke
  name: wp-app
  namespace: wordpress
spec:
  replicas: 4
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - image: wordpress
        name: wordpress
        envFrom:
        # - configMapRef:
        #     name: config
        - secretRef:
            name: secret
        volumeMounts:
        - name: wordpress-storage
          mountPath: /var/www/html
      volumes:
      - name: wordpress-storage
        persistentVolumeClaim:
          claimName: wordpress-pvc



---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-app
  name: wp-app
  namespace: wordpress
spec:
  ports:
  - name: wordpress
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: wordpress
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wp-adminer
    tier: frontend
    env: dev
  name: wp-adminer
  namespace: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      containers:
      - image: adminer
        name: adminer

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: wp-adminer
  name: wp-adminer
  namespace: wordpress
spec:
  ports:
  - name: adminer
    port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30000
  selector:
    app: adminer
  type: NodePort

---

# PersistentVolumeClaim for MariaDB
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

# PersistentVolumeClaim for WordPress
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
  namespace: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi