apiVersion: v1
data:
  WORDPRESS_DB_HOST: d3AtZGI=
  WORDPRESS_DB_NAME: d29yZHByZXNz
  WORDPRESS_DB_PASSWORD: ZW5kMzIx
  WORDPRESS_DB_USER: d3B1c2Vy
kind: Secret
metadata:
  creationTimestamp: null
  name: credentials
