---
# handlers file for LAMP
- name: restart apache2
  become: yes
  service:
    name: apache2
    state: started
    enabled: yes

- name: restart mariadb
  become: yes
  service:
    name: mariadb
    state: started
    enabled: yes