---
# defaults file for common
base_packages:
  - cmatrix
  - htop
  - vim
  - kazam
  - filezilla
  - bluefish
  - php8.2
  - php8.2-cli
  - php8.2-common
  - php8.2-fpm
  - php8.2-mysql
  - php8.2-zip
  - php8.2-gd
  - php8.2-mbstring
  - php8.2-curl
  - php8.2-xml
  - php8.2-bcmath
pic_path: "{{ ansible_user_dir }}/Pictures"
servers:
  - galaxy
  - vulcan
  - ameros
