# Use a base image (e.g., Python image)
FROM python:3.9.16

# Set the working directory
WORKDIR /app

# Copy your script into the container
COPY Tkinter_test.py /app/

# Specify the command to run your script
CMD ["python", "Tkinter_test.py"]

