---
dependencies: []
#
galaxy_info:
  author: acandid
  description: Install and Configure MariaDB, Apache and WordPress
  company: "Almir Candido"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.8
  platforms:
    - name: EL
      versions:
        - 7
    - name: Debian
      versions:
        - buster
#
  galaxy_tags:
    - database
    - mysql
    - mariadb
    - httpd
    - wordpress
    - web
    - apache
    - debian
    - centos
    - redhat
#
allow_duplicates: true
